### ISSUE TITLE
Custom maze layout

### ISSUE THREAD

**Issue by ezadoo** [bward2/pacman-js#77]
Is there a way to create a custom maze-shape? And what are the limitations in maze-size?

**Comment by bward2** [comment]
Yes! You can create custom mazes, and you can _**probably**_ create mazes with different sizes. I wrote the logic in gameCoordinator.js to scale with different maze sizes (and different screen sizes). Since I just wanted to re-create the original Pac-Man as closely as possible, I hard-coded a single maze layout at the beginning of gameCoordinator.js: https://github.com/bward2/pacman-js/blob/master/app/scripts/core/gameCoordinator.js#L22

The maze is just an array of characters representing different objects.
X - wall
o - standard pellet
O - power pellet
(space) - empty space

You can modify this array (or separate it out into a separate file along with other arrays for multiple levels!) to change the maze however you want. Have fun!
